"""Add trend_snapshots table

Revision ID: 589ae9f0db0e
Revises: bf59f5541778
Create Date: 2026-06-24 15:43:56.257120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '589ae9f0db0e'
down_revision: Union[str, None] = 'bf59f5541778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trend_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_snapshots_id'), 'trend_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_trend_snapshots_user_id'), 'trend_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_snapshots_user_id'), table_name='trend_snapshots')
    op.drop_index(op.f('ix_trend_snapshots_id'), table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    # ### end Alembic commands ###
