"""Add category status severity to measurements and fix file sizes

Revision ID: bf59f5541778
Revises: e70bfd97a85d
Create Date: 2026-06-24 15:38:00.156953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf59f5541778'
down_revision: Union[str, None] = 'e70bfd97a85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_measurements', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('report_measurements', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('report_measurements', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('report_measurements', sa.Column('delta_percent', sa.Float(), nullable=True))
    op.alter_column('reports', 'file_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('reports', 'page_count',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'page_count',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('reports', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('report_measurements', 'delta_percent')
    op.drop_column('report_measurements', 'severity')
    op.drop_column('report_measurements', 'status')
    op.drop_column('report_measurements', 'category')
    # ### end Alembic commands ###
