"""Add file_hash file_size page_count to reports

Revision ID: e70bfd97a85d
Revises: 46d8677f5c7e
Create Date: 2026-06-24 15:33:59.710872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70bfd97a85d'
down_revision: Union[str, None] = '46d8677f5c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('reports', sa.Column('file_size', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('page_count', sa.Float(), nullable=True))
    op.create_index(op.f('ix_reports_file_hash'), 'reports', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_file_hash'), table_name='reports')
    op.drop_column('reports', 'page_count')
    op.drop_column('reports', 'file_size')
    op.drop_column('reports', 'file_hash')
    # ### end Alembic commands ###
