"""Add SharedLink

Revision ID: efca9663f6c7
Revises: 589ae9f0db0e
Create Date: 2026-06-25 00:04:57.158502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efca9663f6c7'
down_revision: Union[str, None] = '589ae9f0db0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_links_id'), 'shared_links', ['id'], unique=False)
    op.create_index(op.f('ix_shared_links_report_id'), 'shared_links', ['report_id'], unique=False)
    op.create_index(op.f('ix_shared_links_token'), 'shared_links', ['token'], unique=True)
    op.create_index(op.f('ix_shared_links_user_id'), 'shared_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_links_user_id'), table_name='shared_links')
    op.drop_index(op.f('ix_shared_links_token'), table_name='shared_links')
    op.drop_index(op.f('ix_shared_links_report_id'), table_name='shared_links')
    op.drop_index(op.f('ix_shared_links_id'), table_name='shared_links')
    op.drop_table('shared_links')
    # ### end Alembic commands ###
