'use client';

import { useParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { getReportDetails } from '@/services/reports';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { FileText, Calendar, Database, Activity } from 'lucide-react';
import { useAuth } from '@/features/auth/AuthProvider';

export default function ReportDetailsPage() {
  const params = useParams();
  const reportId = params.id as string;
  const { user } = useAuth(); // Ensure auth checks

  const { data: report, isLoading, error } = useQuery({
    queryKey: ['report', reportId],
    queryFn: () => getReportDetails(reportId),
    enabled: !!reportId && !!user,
  });

  if (isLoading) {
    return <div className="p-12 text-center text-gray-500">Loading report details...</div>;
  }

  if (error || !report) {
    return (
      <div className="p-12 text-center text-red-500">
        <p className="text-lg font-medium">Failed to load report</p>
        <p className="text-sm mt-2">The report may not exist or you do not have permission to view it.</p>
      </div>
    );
  }

  const getSeverityColor = (severity: string | null) => {
    switch (severity) {
      case 'NORMAL': return 'bg-green-100 text-green-800';
      case 'MILD': return 'bg-yellow-100 text-yellow-800';
      case 'MODERATE': return 'bg-orange-100 text-orange-800';
      case 'SEVERE': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8 space-y-8">
      {/* Metadata Section */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900 mb-6">Report Overview</h1>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Upload Date</CardTitle>
              <Calendar className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-lg font-bold">{new Date(report.created_at).toLocaleDateString()}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Status</CardTitle>
              <Activity className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-lg font-bold uppercase">{report.status}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Pages</CardTitle>
              <FileText className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-lg font-bold">{report.page_count || 1}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Size</CardTitle>
              <Database className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-lg font-bold">{report.file_size ? `${(report.file_size / 1024).toFixed(2)} KB` : 'N/A'}</div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Summary Section */}
      {report.patient_summary && (
        <Card className="border-blue-100 bg-blue-50/30">
          <CardHeader>
            <CardTitle className="text-xl text-blue-900">Clinical Summary</CardTitle>
            <CardDescription>Evidence-backed interpretation generated by ClariMed</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6 text-gray-800">
            <div>
              <h3 className="font-semibold text-lg">Overall Assessment</h3>
              <p className="mt-1">{report.patient_summary.overall_assessment}</p>
            </div>
            
            {report.patient_summary.key_findings?.length > 0 && (
              <div>
                <h3 className="font-semibold text-lg">Key Findings</h3>
                <ul className="list-disc pl-5 mt-2 space-y-1">
                  {report.patient_summary.key_findings.map((finding: { biomarker: string, finding_summary: string, value: number, unit: string }, i: number) => (
                    <li key={i}>
                      <strong>{finding.biomarker}:</strong> {finding.finding_summary}{' '}
                      <span className="text-sm text-gray-500">(Value: {finding.value} {finding.unit})</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {report.patient_summary.follow_up_considerations?.length > 0 && (
              <div>
                <h3 className="font-semibold text-lg">Follow-up Considerations</h3>
                <ul className="list-disc pl-5 mt-2 space-y-1">
                  {report.patient_summary.follow_up_considerations.map((consideration: string, i: number) => (
                    <li key={i}>{consideration}</li>
                  ))}
                </ul>
              </div>
            )}

            <div className="text-xs text-gray-500 mt-6 pt-4 border-t border-blue-200">
              <strong>Disclaimer:</strong> {report.patient_summary.disclaimer}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Measurements Table */}
      <Card>
        <CardHeader>
          <CardTitle>Extracted Measurements</CardTitle>
          <CardDescription>Structured data extracted from the clinical report</CardDescription>
        </CardHeader>
        <CardContent>
          {report.measurements.length === 0 ? (
            <div className="text-center py-8 text-gray-500">
              No measurements found in this report.
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Biomarker</TableHead>
                  <TableHead>Category</TableHead>
                  <TableHead className="text-right">Value</TableHead>
                  <TableHead>Unit</TableHead>
                  <TableHead>Reference Range</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Severity</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {report.measurements.map((m) => (
                  <TableRow key={m.id}>
                    <TableCell className="font-medium capitalize">{m.biomarker_name}</TableCell>
                    <TableCell className="capitalize">{m.category || '-'}</TableCell>
                    <TableCell className="text-right">{m.value}</TableCell>
                    <TableCell>{m.unit || '-'}</TableCell>
                    <TableCell>
                      {m.reference_low !== null && m.reference_high !== null 
                        ? `${m.reference_low} - ${m.reference_high}` 
                        : 'N/A'}
                    </TableCell>
                    <TableCell>
                      <Badge variant={m.abnormal_flag ? "destructive" : "secondary"}>
                        {m.abnormal_flag ? 'Abnormal' : 'Normal'}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      {m.severity ? (
                        <Badge className={getSeverityColor(m.severity)} variant="outline">
                          {m.severity}
                        </Badge>
                      ) : (
                        <span className="text-gray-400">-</span>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

    </div>
  );
}
